name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Use the Node.js version your project requires
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Bump version
    #   run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

    - name: Authenticate with npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc

    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ vars.NPM_RELEASE }}
      run: npm publish

    - name: Tag the release
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
        git push origin v${{ github.event.inputs.version }}
